[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"] # list of folders that contain the packages (["."] by default)

[project]
name = "dagent" # appears on pip list only
dynamic = ["version"]
dependencies = [
  "langchain==0.3.26",
  "langchain-ollama==0.3.4",
  "langgraph==0.5.2",
  "pydantic==2.11.7",
  "langchain-core==0.3.68",
  "numpy==2.3.1",
  "langchain_community==0.3.27",
  "tracer @ git+https://github.com/AhmedYasserrr/tracer.git@v0.1.0",
  "python-dotenv==1.1.1",
  "PyYAML==6.0.2",
  "langchain_anthropic==0.3.17",
  "langchain_openai==0.3.10",
  "langchain_huggingface==0.3.0",
  "streamlit==1.52.1",
  "mcp>=1.0.0",
  "Pillow>=10.0.0",                                                  # Vision/Image processing support
]

requires-python = ">=3.12"
authors = [
  { name = "Omar Abdelgawad", email = "omar.abdelgawad@ejust.edu.eg" },
  { name = "Eyad Hussein", email = "eyad.hussein@ejust.edu.eg" },
  { name = "Ahmed Hassan", email = "Ahmed.hasan@ejust.edu.eg" },
  { name = "Ahmed Gamea", email = "Ahmed.gamea@ejust.edu.eg" },
  { name = "Abdelaziz Serour", email = "abdelaziz.serour@ejust.edu.eg" },
]
description = "A Python package for agents that have os-level knowledge."
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["agents", "flow", "llm", "ollama", "knowledge"]
classifiers = ["Programming Language :: Python :: 3.12"]

[project.scripts]
osassis = "dagent.__main__:main"

[dependency-groups]
dev = ["mypy", "ruff", "pytest", "pytest-cov", "tox", "pre-commit"]

[tool.setuptools.package-data]
dagent = ["py.typed", "configs/*.yaml", "prompts/**/*.yaml"]
[tool.setuptools.dynamic]
version = { attr = "dagent.__version__" }

[project.urls]
Repository = "https://github.com/AhmedMo1242/os_assistant"

###################################################################################################
[tool.pytest.ini_options]
addopts = "--cov=dagent" #include all packages under src directory
testpaths = ["tests"]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.ruff]
src = ["src"]
extend-exclude = ["notebooks"]

[tool.ruff.lint]
extend-select = ["UP", "I"]
