DOMAINS:
  - file_system
  - users
  - packages
  - network

LOGS_DIR: "domain_logs"
TEMPERATURE: 0
GRAPH_VISUALIZE: False

# Assistant mode:
# 0 = Both code tool + RAG
# 1 = Code tool only
# 2 = RAG only
# 3 = Basic model only
ASSISTANT_MODE: 0

CODE_AGENT:
  MAX_CONSECUTIVE_ERRORS: 5